### PR TITLE
IoTransaction/Brambl PB Validation

### PR DESCRIPTION
**Pull request by DiademShoukralla**
Added the required PB scala validation rules to brambl models

## Purpose

During TransactionSyntaxValidation, certain fields within a transaction are required/assumed to be present. For example, when validating a Transaction's schedule, we must assume that the path Datum > Event > Schedule exists for the transaction. These requirements will be done via PB validation.

## Approach

Conservatively convert some fields in the IoTransaction model to be required. These fields were identified during TransactionSyntaxInterpreter work. These fields are:

- IoTransaction.datum 
- Datum.IoTransaction.event
- Event.IoTransaction.schedule
- SpentTransactionOutput.KnownIdentifier
- SpentTransactionOutput.attestation
- SpentTransactionOutput.value
- UnspentTransactionOutput.address
- UnspentTransactionOutput.value
- Attestation.Predicate.lock
- Value.Token.quantity
- Value.Asset.quantity

Edit: Validation rules (required) were added to all brambl models 

## Testing

- Ran `cd build/scala` and `sbt publishLocal` => local build successful
- After pushing, I used JitPack in my local quivr4s branch to consume these models

Example of newly generated models:
image
Example of how they will be accessed now:
image

## Tickets
* Closes TSDK-286

### CODE REVIEW

**Review by SeanCheatham — APPROVED** [review]

**Review by nandotorterolo — APPROVED** [review]
Ticket duplicated with https://topl.atlassian.net/browse/BN-834, I assigned to you, feel fee to close it.

Some questions


- Asset quivr.models.SmallData metadata = 3 optional?
- Datum SpentOutput 
       SpentTransactionOutput, optional?
       UnspentTransactionOutput optional?
- Event 
   TransactionOutput32, could you add this comment // list of optional values
   TransactionOutput64, could you add this comment // list of optional values
   metadata optional?

- IoTransaction
  SpentTransactionOutput, could you add this comment // list of optional values
  UnspentTransactionOutput , could you add this comment // list of optional values
  
SpentTransactionOutput
- SpentOutput optional?

UnspentTransactionOutput
- UnspentOutput optional?

Thanks

**Comment by DiademShoukralla** [comment]
@nandotorterolo Thanks for the review! In reference to me leaving some fields as optional; this was because I originally didn't intend for this to be brambl complete - only enough to satisfy TransactionSyntaxInterpreter. But since this duplicates BN-834, I will add the rules to the models and fields I think are necessary

**Review by nandotorterolo — APPROVED** [review]
Looks good, 
Only find 1 difference when quiv4s define :  List[Option[A]]
Example 
```
sealed abstract class Attestation {
  val lock: Lock
  val responses: List[Option[Proof]]
}
```
which will me mappen on protobuf
>     repeated quivr.models.Proof responses = 2;

repeated will generate a list, but the Proof will be not optional.
maybe it cause problems, I am not sure

**Comment by nandotorterolo** [comment]
> Looks good, Only find 1 difference when quiv4s define : List[Option[A]] Example
> 
> ```
> sealed abstract class Attestation {
>   val lock: Lock
>   val responses: List[Option[Proof]]
> }
> ```
> 
> which will be mapped on protobuf
> 
> > ```
> > repeated quivr.models.Proof responses = 2;
> > ```
> 
> repeated will generate a list, but the Proof will be not optional. maybe it causes problems, I am not sure

no worries about it, just discuss it with Sean, and there is no problem

**Pull request merged**
