### PR TITLE
[BN-1018] Add gRPC Health Check Proto

### PR DESCRIPTION
**Pull request by admiraladmirable**
## Purpose
Add health check proto. 

## Approach
The proto comes from: https://github.com/grpc/grpc/blob/master/doc/health-checking.md

## Testing
Built locally, implemented in Bifrrost, deployed to GKE and ensured that the `grpc` liveliness/readiness probes succeeded.

### CODE REVIEW

**Review by nandotorterolo — APPROVED** [review]
Great PR, some suggestions.

- files structure 
- enumeration comments

Package names should be in lowercase. Package names should have unique names based on the project name, and possibly based on the path of the file containing the protocol buffer type definitions.

https://protobuf.dev/programming-guides/style/#packages

In other folders proto file are organized by service/models, maybe you can do something like this.

- proto
    - health
        - service
            - health_rpc.proto
        - models
            - models.proto
            

> models.proto

```
enum ServingStatus {
    // UNKNOWN means that there was a timeout hitting the head of the chain..
    UNKNOWN = 0;
    // SERVING means that all services are running as expected
    SERVING = 1;
    // NOT_SERVING means...
    NOT_SERVING = 2;
    // SERVICE_UNKNOWN means,  // Used only by the Watch method.
    SERVICE_UNKNOWN = 3;  
  }
```

> health_rpc.proto  
  
```
syntax = "proto3";

package co.topl.health.services;

service Health {
  rpc Check(HealthCheckRequest) returns (HealthCheckResponse);

  rpc Watch(HealthCheckRequest) returns (stream HealthCheckResponse);
}

message HealthCheckRequest {
 // service is a string that we must/should send for this reason.
  string service = 1;
}

message HealthCheckResponse {
  ServingStatus status = 1;
}

```

**Comment by admiraladmirable** [comment]
> Great PR, some suggestions.
> 
>     * files structure
> 
>     * enumeration comments
> 
> 
> Package names should be in lowercase. Package names should have unique names based on the project name, and possibly based on the path of the file containing the protocol buffer type definitions.
> 
> https://protobuf.dev/programming-guides/style/#packages
> 
> In other folders proto file are organized by service/models, maybe you can do something like this.
> 
>     * proto
>       
>       * health
>         
>         * service
>           
>           * health_rpc.proto
>         * models
>           
>           * models.proto
> 
> 
> > models.proto
> 
> ```
> enum ServingStatus {
>     // UNKNOWN means that there was a timeout hitting the head of the chain..
>     UNKNOWN = 0;
>     // SERVING means that all services are running as expected
>     SERVING = 1;
>     // NOT_SERVING means...
>     NOT_SERVING = 2;
>     // SERVICE_UNKNOWN means,  // Used only by the Watch method.
>     SERVICE_UNKNOWN = 3;  
>   }
> ```
> 
> > health_rpc.proto
> 
> ```
> syntax = "proto3";
> 
> package co.topl.health.services;
> 
> service Health {
>   rpc Check(HealthCheckRequest) returns (HealthCheckResponse);
> 
>   rpc Watch(HealthCheckRequest) returns (stream HealthCheckResponse);
> }
> 
> message HealthCheckRequest {
>  // service is a string that we must/should send for this reason.
>   string service = 1;
> }
> 
> message HealthCheckResponse {
>   ServingStatus status = 1;
> }
> ```

@nandotorterolo Thanks for the review!

I'll update the folder format of the modes/services.

One note though, I don't believe that the built in gRPC health check in Kubernetes supports customizing the package/service path. I believe it must be `grpc.health.v1.Health`. Hopefully this is okay.

**Comment by nandotorterolo** [comment]
ok, I didn't know about Kubernetes customizations. 
So, Kubernetes needs
-  a package with this namespace:  `grpc.health.v1.Health`
- the file should be in a folder with this path: 'google/..'

> 
> @nandotorterolo Thanks for the review!
> 
> I'll update the folder format of the modes/services.
> 
> One note though, I don't believe that the built in gRPC health check in Kubernetes supports customizing the package/service path. I believe it must be `grpc.health.v1.Health`. Hopefully this is okay.

**Comment by admiraladmirable** [comment]
> ok, I didn't know about Kubernetes customizations. So, Kubernetes needs
> 
>     * a package with this namespace:  `grpc.health.v1.Health`
> 
>     * the file should be in a folder with this path: 'google/..'
> 
> 
> > @nandotorterolo Thanks for the review!
> > I'll update the folder format of the modes/services.
> > One note though, I don't believe that the built in gRPC health check in Kubernetes supports customizing the package/service path. I believe it must be `grpc.health.v1.Health`. Hopefully this is okay.

Yes, however the `google/` folder path isn't necessarily required, but I just simplified it instead of a more complicated file structure. If we want to, I could structure the folder like:

```
grpc
| -- health
    | -- v1
```

Or whichever format makes more sense.

**Pull request merged**
